import { IProyectsInfo } from '../components/ProyectsData/ProyectsData';

export const proyectsInfo: IProyectsInfo[] = [
    {
        id: 1,
        date: 'Mar 2022 - Dic 2022',
        img: { src: '/cars-booking.gif', alt: 'gift pagina web' },
        title: 'aplicación web - cars booking',
        company: 'Digital House',
        description:
            '"Desarrollo completo de un sitio web para alquiler de autos, utilizando la metodología ágil Scrum. Los usuarios podrán acceder a una plataforma fácil de usar que les permitirá crear una cuenta, reservar un auto y ver un registro completo de sus reservas anteriores."',
        technologies: ['react', 'sass', 'api-rest', 'spring boot', 'mysql'],
        github: 'https://github.com/jesyn/carsbooking-frontend',
        url: '',
    },
    {
        id: 2,
        date: 'Feb 2023 - Mayo 2023',
        img: { src: '/github-search.jpg', alt: 'gift pagina web' },
        title: 'buscador de usuarios de github',
        company: 'Frontend mentor',
        description:
            '"Busca cualquier usuario de Github y visualiza su información en la tarjeta que se encuentra debajo. Podrás ver información relevante del usuario en la tarjeta y también el historial de búsquedas realizadas".',
        technologies: ['react', 'api-rest'],
        github: 'https://github.com/jesyn/github_user_search',
        url: 'https://github-user-search-jesyn.vercel.app/',
    },
    {
        id: 3,
        date: 'Feb 2023 - Mayo 2023',
        img: { src: '/rick-and-morty.gif', alt: 'gift pagina web' },
        title: 'rick and morty',
        company: 'Digital House',
        description:
            '"Página que muestra una colección de personajes de la popular serie "Rick and Morty". Los usuarios pueden buscar entre los diferentes personajes utilizando un buscador y seleccionar sus favoritos para agregarlos a una lista personalizada."',
        technologies: ['react', 'redux', 'typescript', 'api-rest', 'jsdoc'],
        github: 'https://github.com/jesyn/Rick-and-Morty',
        url: 'https://rick-and-morty-jesyn.vercel.app/',
    },
    {
        id: 4,
        date: 'Ene 2023 - Mar 2023',
        img: { src: '/testimonial.gif', alt: 'gift pagina web' },
        title: 'Control deslizante de testimonios',
        company: 'Frontend mentor',
        description:
            '"Testimonios en forma de diapositivas que se pueden navegar utilizando controles deslizantes. Se adapta automáticamente al tamaño de pantalla del dispositivo del usuario."',
        technologies: ['react', 'sass'],
        github: 'https://github.com/jesyn/-coding-bootcamp-testimonials-slider',
        url: 'https://jesyn.github.io/-coding-bootcamp-testimonials-slider/',
    },
    {
        id: 5,
        date: 'May 2023 - Jun 2023',
        img: { src: '/porfolio.jpg', alt: 'imagen pagina web' },
        title: 'porfolio',
        company: 'Freelancer',
        description:
            '"Sitio web estaría construido utilizando Gatsby, donde se podrá ver en detalle mi infomarción personal, descarga de CV y experiencia."',
        technologies: ['gatsby', 'react', 'typescript', 'sass'],
        github: 'https://github.com/jesyn/jm-portfolio',
        url: 'https://jm-portfolio-85f3gfx8w-jesyn.vercel.app/',
    },
    {
        id: 6,
        date: 'May 2023 - actualiadad',
        img: { src: '/logo-pizza.jpg', alt: 'logo pizzería' },
        title: 'pizzería rémolo',
        company: 'Id for ideas',
        description: '"Aplicación para el armado y pedido de pizzas"',
        technologies: [
            'nextjs',
            'tailwind',
            'typescript',
            'design system',
            'storybook',
            'jest',
            'testing-library',
            'husky',
        ],
        github: '',
        url: '',
        underConstruction: true,
    },
];
